[package]
name = "rcc"
version = "0.0.1"
authors = ["1011X <1011XXXXX@gmail.com>"]

[dependencies]
regex = "0.1.80"
nom = { version = "2.1.0", features = ["regexp"] }
rel_isa = { git = "https://github.com/1011X/REL-16" }
